name: HTML Proofer

on: [push, pull_request]

jobs:
  Validate_HTML:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      # Use GitHub Actions' cache to shorten build times and decrease load on servers
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      # Build the site
      - uses: lemonarc/jekyll-action@1.0.0
      - name: Check HTML
        uses: chabad360/htmlproofer@master
        with:
          directory: "./_site"
          arguments: --check-html --url-ignore "/https://www.linkedin.com/in/niek-candaele-2baa131a1/"
